version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.0
    commands:
      - echo Install a runtime, even though I do not need one
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - aws cloudformation validate-template --template-body file://vpc.yml 
  build:
    commands:
      - echo Build started on `date`
      - echo I can see these files `ls -la`
      - touch hello.txt
      - echo "Hello, World!" > hello.txt
      - zip hello.zip hello.txt
      - aws cloudformation deploy --template-file ./vpc.yml --stack-name logformation
  post_build:
    commands:
      - echo Build completed on `date`
      - echo I can see these files `ls -la`
artifacts:
  files:
    - hello.zip
