---
AWSTemplateFormatVersion: 2010-09-09
# Simple VPC cloudformation template
Resources:
  # My VPC:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-VPC2'
